"""empty message

Revision ID: 1c635f7909fb
Revises: 73fad5a536ca
Create Date: 2025-04-03 10:31:29.260859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c635f7909fb'
down_revision = '73fad5a536ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_group_activity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_group_activity', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###
