"""Group private

Revision ID: 537f43cdd80c
Revises: 1c635f7909fb
Create Date: 2025-04-05 19:13:02.012122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537f43cdd80c'
down_revision = '1c635f7909fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
